version: "3.8"
services:

  redis:
    image: redis

  mysql:
    image: mysql:5.7.29
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: larabase
      MYSQL_USER: larauser
      MYSQL_PASSWORD: larasecret
      MYSQL_ROOT_PASSWORD: lararootsecret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  php:
    image: lara8buster
    build:
      context: docker
      dockerfile: ./docker/php.dockerfile
    environment:
      XDEBUG_CONFIG: "log_level=0 client_host=host.docker.internal log=/tmp/xdebug.log"
    user: root
    volumes:
      - ./:/app:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:delegated
    ports:
      - 80:80
    depends_on:
      - mysql
      - redis

  artisan:
    image: lara8buster
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal log=/tmp/xdebug.log"
    volumes:
      - ./:/app:cached
    depends_on:
      - mysql
    working_dir: /
    user: laravel
    entrypoint: ['php', '/app/artisan']
